# Generated by Django 2.0.5 on 2018-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_type', models.CharField(choices=[('M', 'Mono-phasic'), ('B', 'Bi-phasic'), ('T', 'Tri-phasic')], max_length=1)),
                ('load', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='panel_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_type', models.CharField(choices=[('M', 'Mono-phasic'), ('B', 'Bi-phasic'), ('T', 'Tri-phasic')], max_length=1)),
            ],
        ),
    ]
